name: AventCube
main: AventCube\Main
version: 1.0.0
api: [1.12.0]
author: Asparanc
description: "Main plugin for AventCube"
commands:
  wallet:
   permission: asparanc.ac.wallet
   description: "See your current money"
   default: true
  setrank:
   permission: asparanc.ac.setrank
   description: "Set rank for a player"
   default: op
  setwarp:
   permission: asparanc.ac.setwarp
   description: "Create a new warp"
   default: op
  tpw:
   permission: asparanc.ac.tpw
   description: "Teleport you in other world"
   default: op
  setwarptp:
   permission: asparanc.ac.setwarptp
   description: "Set the start point for a warp hub"
   default: op
